name: Keep the versions up-to-date
 
on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
