name: Log Version

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-beta'

jobs:
  log_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log version
        run: |
          echo "Tag: ${{ github.ref }}"
          echo "Version: ${{ github.ref_name }}"
